AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EBSVolumeSize:
    Type: Number
    Default: 20
    Description: Size of EBS Volume to attach.

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: SecurityGroups to attach to EC2 launched from this template.

  InstanceType:
    Type: String
    Default: "t2.micro"
    Description: InstanceType to create EC2 from.

  InstanceAmiId:
    Type: AWS::SSM::Parameter::Value<EC2::Image::Id>
    Description: InstanceType to create EC2 from.
    Default: LatestAmazonAmiId

Resources:
  LaunchTemplateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  LaunchTemplateInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${AWS::StackName}-EC2-LaunchTemplate-InstanceProfile
      Roles:
        - !Ref LaunchTemplateRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-EC2-LaunchTemplate
      LaunchTemplateData:
        InstanceMarketOptions:
          MarketType: spot
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: !Ref EBSVolumeSize
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
            DeviceName: /dev/sda
        Monitoring:
          Enabled: true
        ImageId: !Ref InstanceAmiId
        InstanceType: !Ref InstanceType
        SecurityGroupIds: !Ref SecurityGroupIds
        IamInstanceProfile: 
          Arn: !GetAtt  LaunchTemplateInstanceProfile.Arn
