AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
    Default: ""
    AllowedPattern: "^$|^[a-z0-9]+[a-z0-9-]{1,61}[a-z0-9]+$"
    Description: Name of S3 Bucket. The Account ID will be appended behind this string to make this name globally unique.

  S3ReadOnlyBucketPolicyPrincipalArns:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: RootUserArnStringList
    Description: Parameter Store of list of principal ARNs with Read Only access to this bucket.

  S3ReadWriteBucketPolicyPrincipalArns:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: RootUserArnStringList
    Description: Parameter Store of list of principal ARNs with Read Only access to this bucket.

Conditions:
  CreateS3Bucket: !Not
    - !Equals
      - !Ref S3BucketName
      - ""

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Condition: CreateS3Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}-${AWS::AccountId}

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateS3Bucket
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: 
              AWS: !Ref S3ReadOnlyBucketPolicyPrincipalArns
          - Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: 
              AWS: !Ref S3ReadWriteBucketPolicyPrincipalArns
