AWSTemplateFormatVersion: 2010-09-09

Resources:
  VcsDeploymentRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub Vcs-${AWS::AccountId}

  VcsDeploymentPipeline:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !GetAtt VcsDeploymentPipelineRole.Arn
      Name: VcsDeploymentPipeline
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
      Source:
        Type: CODECOMMIT
        Location: !GetAtt VcsDeploymentRepository.CloneUrlHttp
        BuildSpec: |
          version: 0.1
          phases:
            build:
              commands:
                - aws cloudformation describe-stacks

  VcsDeploymentPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
