AWSTemplateFormatVersion: 2010-09-09

Resources:
  DeployS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub deploy-${AWS::AccountId}

  DeployS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeployS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${DeployS3Bucket}/*"
            Principal:
              AWS: !GetAtt VcsDeploymentCodeBuildProjectRole.Arn

  VcsCloudformationTemplateRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub VcsCloudformationTemplate-${AWS::AccountId}

  VcsCloudformationDeploymentRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub VcsCloudformationDeployment-${AWS::AccountId}

  VcsDeploymentCodeBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess

  CodeBuildStartBuildRoleForCloudwatchEvents:
    Type: AWS::IAM::Role

    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [events.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  VcsDeploymentCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !GetAtt VcsDeploymentCodeBuildProjectRole.Arn
      Name: VcsDeploymentCodeBuildProject
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
      Source:
        Type: CODECOMMIT
        Location: !GetAtt VcsCloudformationDeploymentRepository.CloneUrlHttp
        BuildSpec: !Sub
          - |
            version: 0.1
            phases:
              build:
                commands:
                  - git diff --name-only HEAD~1 > .changes
                  -  |
                      while read p; do
                        [ -f /tmp/template.yaml ] && rm /tmp/template.yaml
                        [ -f /tmp/template.deploy.yaml ] && rm /tmp/template.deploy.yaml
                        [ -f /tmp/parameters.yaml ] && rm /tmp/parameters.yaml

                        stackName=$(cat $p | jq -rc .StackName)
                        templateFilePath=$(cat $p | jq -rc .TemplateFilePath)
                        parameters=$(cat $p | jq -rc .Parameters)

                        [ -n "$stackName" ] || continue
                        echo "Stack Name: " $stackName

                        [ -n "$templateFilePath" ] || continue
                        echo "Template File Path: " $templateFilePath

                        [ -n "$parameters" ] || continue
                        echo "Parameters: " $parameters
                        echo $parameters > /tmp/parameters.yaml

                        echo "Retrieving Template.."
                        aws codecommit get-file --repository-name ${VcsCloudformationTemplateRepositoryRefName} --file-path "$templateFilePath" --query fileContent --output text | base64 -d > /tmp/template.yaml
                        [ -n "$(cat /tmp/template.yaml)" ] || continue

                        aws cloudformation package --template-file /tmp/template.yaml --s3-bucket ${DeployS3BucketS3Uri} > /tmp/template.deploy.yaml

                        echo "Checking if Stack with name $stackName exists.."
                        aws cloudformation describe-stacks --stack-name "$stackName" > /tmp/null
                        if [ $? -eq 0 ]; then
                          aws cloudformation update-stack --template-body file:///tmp/template.deploy.yaml --stack-name "$stackName" --capabilities CAPABILITY_IAM --parameters "$parameters"
                        else
                          aws cloudformation create-stack --template-body file:///tmp/template.deploy.yaml --stack-name "$stackName" --capabilities CAPABILITY_IAM --parameters "$parameters"
                        fi
                      done <.changes
          - VcsCloudformationTemplateRepositoryRefName: !GetAtt VcsCloudformationTemplateRepository.Name
            DeployS3BucketS3Uri: !Ref DeployS3Bucket

  VcsCloudformationDeploymentCommitEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger CodeBuild for cloudformation deployments on pushes to the deployment repository.
      State: ENABLED
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        detail:
          repositoryId: 
            - !Ref VcsCloudformationDeploymentRepository
          referenceType: 
            - branch
          referenceName: 
            - main
      Targets:
        - Arn: !GetAtt VcsDeploymentCodeBuildProject.Arn
          RoleArn: !GetAtt CodeBuildStartBuildRoleForCloudwatchEvents.Arn
          Id: VcsDeploymentCodeBuildProject
