AWSTemplateFormatVersion: 2010-09-09

Parameters:
  NumberOfSubnetsToCreate:
    Type: Number
    AllowedValues:
      - 2
      - 4
      - 8
    Default: 2
    Description: Number of Subnets we wish to create in this VPC.

Conditions:
  BuildSubnetGroupB:
    !Or [
      !Equals [!Ref NumberOfSubnetsToCreate, 4],
      !Equals [!Ref NumberOfSubnetsToCreate, 8],
    ]
  BuildSubnetGroupCD: !Equals [!Ref NumberOfSubnetsToCreate, 8]

Resources:
  BaseVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default

  SubnetGroupA1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.0.0/19
      AvailabilityZone: ap-southeast-1a

  SubnetGroupA2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.32.0/19
      AvailabilityZone: ap-southeast-1b

  SubnetGroupB1:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupB
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.64.0/19
      AvailabilityZone: ap-southeast-1a

  SubnetGroupB2:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupB
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.96.0/19
      AvailabilityZone: ap-southeast-1b

  SubnetGroupC1:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupCD
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.128.0/19
      AvailabilityZone: ap-southeast-1a

  SubnetGroupC2:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupCD
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.160.0/19
      AvailabilityZone: ap-southeast-1b

  SubnetGroupD1:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupCD
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.192.0/19
      AvailabilityZone: ap-southeast-1a

  SubnetGroupD2:
    Type: AWS::EC2::Subnet
    Condition: BuildSubnetGroupCD
    Properties:
      VpcId: !Ref BaseVPC
      CidrBlock: 10.0.224.0/19
      AvailabilityZone: ap-southeast-1b
